# spring configuration
spring:
   application:
      name: mysite06

   devtools:
      restart:
         enabled: true		
      livereload:
         enabled: true

   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp	

   aop:
      auto: true
      proxy-target-class: true 

# server configuration
server:
   port: 8080
   servlet:
      context-path: /